---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgCkxEm53tIdqW0Su0Cbf+njmTK+xP3yr3ZphSXaQ+AfiP0fPs8vLz1TQzpNaFCtbRD7zizPEPLQiaUuVyvBQPT60uRHk/7cKe1CvrAV2ITU7+Sg07xeTFh1aZ0Vd7+lS/f9HDWOHqAem+lFuRul0PygN7kFpGsiRK8DLdCtWPOq2M/8ScQAiS0HzpvxdX/SdVaXaN2/C0PTRkGm4bVRw8epHracqEeOvuE1hnxzdcd9J1Ih3kEMa94NHKQyXigvwx8bV25swSXN+YDH/N6dzNf2NBWF53Nq81kR9Mf61b3dGZNtl+KLXS8QWwQEJmdPalhv108DqN/UWwfq6921kOlfQcNaGIlG0zI2ZyfaomyXVS6t4MqinR4+NxoaTPWkvHkwM9xHSEp3zyFIJNUiXA3Uv1vZFE752KQ2ou+N74LVcZtlH6ngeHEEAVmWDtx1HMH/6QQeBuMPehFz/DYwZ2lIlPWYEA8X21Cuup0cwGXyYXr5WtwdHhrVdGMuUCvOosQeqw62N2f5KiMWTyPv7Lm1iObQF0BzNNsfyLEekt94PGZT2Nm6RiTyJ/42UOtNoeMwsjwrNYFbD7jDT804DybjunZOEBOQIw9fc7gvlQxKLEH3ejh7nNnNBcE8EcQtqShCpLB9XD1YhDDyvgcKxGsiF8fygYfVFWHsmffa6tnDZHRSRBszKCnThCKIRZZtWwb380IEMbqpU9kHVefjM1ehv+cgFpsEG8ZFI7ni6JVzKWd/EaGWaK9BU4BP4N3ZH1V8BSGpLvRMPOYc09FI/gYqMc3Oll3gWEj1BP6OHuaeJ7DKj/7id13YurRY1nFlWaIzx2TDBGgpWw2sPLfVQCg3CX8RhAZ8o+e+gBLqSdUuX+oJCz58OD3QuAMXBJXLI4175mf4Ma9EuuPb1hTDQMlDLL4uXMpdaVS0mlGKcl5jcAoLLzFuti/k5X9FCxV+YAYE4Xpudu8VwOEHSiHZ2hT3hVzgKOatH9RXF3Q=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
    type: kubernetes.io/dockerconfigjson
