---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
  namespace: uniselec-admin
spec:
  encryptedData:
    .dockerconfigjson: AgBrThgJcX6oog3izVDZucb/IfGz78k8WXZkzmlaVWSDEZg131+VJZIJz5PJEjXyWpLq/c0i+ERWWS84ptH/ip2OO/7kx5Q4GA6twDMWViz9C/dRam2vkik7Ps+C9Q3f5xOCgM8tQTN/fhBKYnz9YCwxWbbMHqeCNBo0xkn9gMJh+xrNGniqVZ5nCqQ9dYMJby968lhcexEwIRdg/i8B29UfQScPWLaktan883YKyb7OmUUys9wb4nYIuIxqUEpz0nU9IV80aurpUBaz3uISGeqphKqgOVMUpbM6iZcmbVWLSp5BLqzgRxPdjESk4ZiTlFgUu31uElCBSkLkjG5fBP1eKzIkufkuDDoygx+X7hRuvpkv6w/DCCXtqXHevlOanm6eRHG7qGDBqh7fQAQ43gVdrsYsmfYoyTH/mz1EAl0PUug2bLspP4a52Tw0FS48He62B34QK8i3KBHulvJrsKvoO0pq33SigUHueP8NqYmUHiqza16SrPS3hHK2KYO0zu/+Ovi0b5ORVv5RFhDJ05wdUwdt/fy0y6UXN0E5tmBceAcfeY0kFWsc6BzTQUtEyYBIIo0oyxWf8KbA/VbNXM+Ry0zVeWfQV8JHMV75KOgRkKZXX7SVSVYQguoAg8LFR1Lr1jMd9GqLF9Dzkxh9t51votPN+UB9RkLEVCPY84fzEYOrM9s9TFvHzgPB8XQyQnDPAIphUSw9qYupFhG2AzdH3YDOcCMLRblG21i7wmgylhhrtCc4part5tS2fwjgs/lxeKhl4C0YCh4UCRgudiELcRvx3OkAX3SrL016W5QP/GF6Q7HbnQVzOuEDNd2DLL0/oM7DJ6yGJMsq2e/8xMQX2LfmpX3tLaDORHe2QfV/X7kcBKE669lohg0vDc3ZL82z5sxRQwHg9NMarq2RTCBwSp2qjAS7UrBkBjascLdS45qHrP/GZiEbV1xW5qS/QPrrFNHl6RtLnwENuABMHDEv
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
      namespace: uniselec-admin
    type: kubernetes.io/dockerconfigjson
