---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgAxFI6ROzotVvO7kOEOmRoaXdm/CZ8U+V65Msf9+q/WVjNVMc/ebORrTHPN7TE8/gWX20dJbx8XKOkKztj/jAbm9X6PC4k90cUWCscdnQuGhfLsrOChz+HNBYOmJb+ACcIB15k+Bmq4Oh7e40Jie5Hwy3eHzQlWqAvfVFtxi4k04mQs/M0zuMmjEIQYJIV1oI8uozpgtE1dXgw5NYQmNvDUhowOI8H0lYxHPgE6e59DgER2w9mW1VpGU3iFPni9fKY+B+28jnJUfZQZFFfVnfbk8PaiuLLbkfGfVkrmaE9+02iUTEhfoZhRwUHZHscNAEfsdXM3/AK2nD2zb9F1nFWGPkVuA2PSTm+fL/KyEmf49Fws+8HtC/CoxTXM0ixXcmSGgSZVwukknF5vkIjUE923Q+4VIMYtQ3keksjCb0RpcmTt/zYlCyvCOK7+Ixjwgmt4+f8YQ/w5UOzX0Oo7CMNn9sXq/n0Z7Qmm0wXi9VcVdr2HVy4Tj8rBG5rwGZkGbhXFbwkDapO06EiSf2Gi1fQTL7AH5d4iOEyaTueanoCShFLmpuM5ogtamSObZkfbYUD6DMdUkDuIbs1VwD7IdEKdsReQmpzjVatpVoB2gF5t78oZji9OPhIID+8k20UzTOn2gKYDReYWVmySg1Ulw6Z7dS9udFuAVCeDpinFcxNHxHNxKDeBO+EbCrpVe6bFhCe+FEi4GXhJkwdd5j3oue0s4BL6qQE1fqyL0SINLqWoemCpIe6sIjIQYsZwppNoMhuJhxzwjoIeKceArtHyrKFkH0ycxa0TItnA2N/KyY0SP9F28RO1Rb7tBavr/8DvFQm8DRybaOSFkPdMdMqKvf5NxWJKjehWfG2fK14hPlA5QPqpIQDY2pSJ+ZQTneZw7BRdoamRGahoIiGx1eTBZNDWXMvsktTcMJIXKQyLVbDv8hBAgzvbYhfxtI4ZAKdw5JXHZSBtu258G7ZN6dqGt6LMKojMBZRcGwEACsB6kq9hVBM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
    type: kubernetes.io/dockerconfigjson
